<a href="https://colab.research.google.com/github/OscarPasasin/etl-data-pipeline-1704862022/blob/main/notebooks/Bodegas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://raw.githubusercontent.com/OscarPasasin/etl-data-pipeline-1704862022/refs/heads/main/data/raw/E_bodegas.csv

In [1]:
import pandas as pd

In [8]:

url = "https://raw.githubusercontent.com/OscarPasasin/etl-data-pipeline-1704862022/refs/heads/main/data/raw/E_bodegas.csv"

df = pd.read_csv(url)

df.head()

  id_bodega       bodega   ubicacion capacidad_m2
0    BOD100   Central 0     Usulután      1292 m2
1    BOD101        Sur 1  San Miguel         2047
2    BOD102    Central 2   Sonsonate       651 m2
3    BOD103  Occidente 3  San Miguel         2250
4    BOD104        Sur 4   Santa Ana          239

In [9]:

#Exploracion de datos
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_bodega     18 non-null     object
 1   bodega        20 non-null     object
 2   ubicacion     20 non-null     object
 3   capacidad_m2  20 non-null     object
dtypes: object(4)
memory usage: 772.0+ bytes

id_bodega       2
bodega          0
ubicacion       0
capacidad_m2    0
dtype: int64

In [11]:

#Limpieza de datos
E_bodegas = df.copy()
print(E_bodegas['id_bodega'].value_counts(dropna=False))

id_bodega
BOD103    2
NaN       2
BOD106    2
BOD100    1
BOD102    1
BOD104    1
BOD105    1
BOD107    1
BOD101    1
BOD108    1
BOD109    1
BOD111    1
BOD112    1
BOD113    1
BOD115    1
BOD116    1
BOD117    1
Name: count, dtype: int64

In [12]:
E_bodegas['capacidad_m2'].value_counts(dropna=False)

capacidad_m2
1783       2
2250       2
2047       1
1292 m2    1
239        1
651 m2     1
1546       1
2181       1
1359       1
2097       1
299        1
1582       1
413 m2     1
1062       1
1635       1
2217       1
788        1
1904       1
Name: count, dtype: int64

In [13]:
#Quitar m2 de capacidad_m2
E_bodegas = df.copy()
E_bodegas['capacidad_m2'] = E_bodegas['capacidad_m2'].str.replace('m2', '')
print(E_bodegas['capacidad_m2'].value_counts(dropna=False))

capacidad_m2
1783     2
2250     2
2047     1
1292     1
239      1
651      1
1546     1
2181     1
1359     1
2097     1
299      1
1582     1
413      1
1062     1
1635     1
2217     1
788      1
1904     1
Name: count, dtype: int64

In [14]:
#Separar válidos y rechazados

validos = E_bodegas[
    E_bodegas['id_bodega'].notna() &
    E_bodegas['bodega'].notna() &
    E_bodegas['ubicacion'].notna() &
    E_bodegas['capacidad_m2'].notna()
].copy()
rechazados = E_bodegas[
    E_bodegas['id_bodega'].isna() |
    E_bodegas['bodega'].isna() |
    E_bodegas['ubicacion'].isna() |
    E_bodegas['capacidad_m2'].isna()
].copy()

In [15]:
#Motivo de rechazo

def motivo(row):

    motivos = []

    if pd.isna(row['id_bodega']):
        motivos.append("id_bodega_vacio")

    return ",".join(motivos)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

In [16]:
validos.to_csv("E_bodegas_curated.csv", index=False)

rechazados.to_csv("E_bodegas_rejects.csv", index=False)

In [17]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:Mg85y5ihbsfGYCeJN4InkDwmJe84QY6F@dpg-d6vijdvkijhs73cshc90-a.oregon-postgres.render.com/etl_data_pipeline_1704862022"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 81.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [24]:
try:
    validos.to_sql('e_bodega_curated', engine, if_exists='replace', index=False)
    print("Table 'e_bodega_curated' created and data inserted successfully.")
except Exception as e:
    print(f"Error creating or inserting data into 'e_bodega_curated': {e}")

Table 'e_bodega_curated' created and data inserted successfully.

In [25]:
try:
    rechazados.to_sql('e_bodega_rejects', engine, if_exists='replace', index=False)
    print("Table 'e_bodega_rejects' created and data inserted successfully.")
except Exception as e:
    print(f"Error creating or inserting data into 'e_bodega_rejects': {e}")

Table 'e_bodega_rejects' created and data inserted successfully.

In [26]:
try:
    df_check = pd.read_sql("SELECT * FROM e_bodega_curated LIMIT 5", engine)
    print("\nFirst 5 rows of 'e_bodega_curated':")
    display(df_check)
except Exception as e:
    print(f"Error querying 'e_bodega_curated': {e}")

First 5 rows of 'e_bodega_curated':

  id_bodega       bodega   ubicacion capacidad_m2
0    BOD100   Central 0     Usulután        1292
1    BOD101        Sur 1  San Miguel         2047
2    BOD102    Central 2   Sonsonate         651
3    BOD103  Occidente 3  San Miguel         2250
4    BOD104        Sur 4   Santa Ana          239